// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMW-DT6od932kDjlAj0nvCNy0mpNjOii4',
    appId: '1:649974319305:web:0c1715ca5169e9ffca6518',
    messagingSenderId: '649974319305',
    projectId: 'fir-authentication-a4c9a',
    authDomain: 'fir-authentication-a4c9a.firebaseapp.com',
    storageBucket: 'fir-authentication-a4c9a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq-tGq2KvDq3fCZsX-CXR80LwB91xi4ZU',
    appId: '1:649974319305:android:0f0ef956f591d056ca6518',
    messagingSenderId: '649974319305',
    projectId: 'fir-authentication-a4c9a',
    storageBucket: 'fir-authentication-a4c9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB54Pfm6nH0hc36sqVBjURLXO3DLAHr72s',
    appId: '1:649974319305:ios:82e31236612df17aca6518',
    messagingSenderId: '649974319305',
    projectId: 'fir-authentication-a4c9a',
    storageBucket: 'fir-authentication-a4c9a.appspot.com',
    iosClientId: '649974319305-b62mlds154jc5cpm0fp7as90q7dp1go3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB54Pfm6nH0hc36sqVBjURLXO3DLAHr72s',
    appId: '1:649974319305:ios:82e31236612df17aca6518',
    messagingSenderId: '649974319305',
    projectId: 'fir-authentication-a4c9a',
    storageBucket: 'fir-authentication-a4c9a.appspot.com',
    iosClientId: '649974319305-b62mlds154jc5cpm0fp7as90q7dp1go3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseLogin',
  );
}
